### ISSUE TITLE
App Crash in Naugat Android 7.1.1 (ConcurrentModificationException)

### ISSUE THREAD

**Issue by cisankit** [CarGuo/RecordWave#10]
Crashing frenquently on the following method : 

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:837)
	at com.shuyu.waveview.AudioWaveView.resolveToWaveData(AudioWaveView.java:254)
	at com.shuyu.waveview.AudioWaveView.access$900(AudioWaveView.java:27)
	at com.shuyu.waveview.AudioWaveView$drawThread.run(AudioWaveView.java:191)

**Comment by CarGuo** [comment]
thanks , i will try to fix it later.

**Comment by cisankit** [comment]
I am using physical device. NEXUS 5x

**Comment by cisankit** [comment]
Any update for the Issue.(Crash on 7.1)

**Comment by CarGuo** [comment]
try v1.1.3
