### ISSUE TITLE
nexus 5 Android 7.1.2 crash

### ISSUE THREAD

**Issue by ForeverLiuyaqi** [CarGuo/RecordWave#13]
Crashing frenquently on the following method :

java.lang.ArrayIndexOutOfBoundsException: length=360; index=360
at java.util.ArrayList.get(ArrayList.java:413)
at com.shuyu.waveview.AudioWaveView.resolveToWaveData(AudioWaveView.java:258)
at com.shuyu.waveview.AudioWaveView.access$900(AudioWaveView.java:27)
at com.shuyu.waveview.AudioWaveView$drawThread.run(AudioWaveView.java:193)

**Comment by CarGuo** [comment]
which version？？

**Comment by ForeverLiuyaqi** [comment]
RecordWave:v1.1.2

**Comment by ForeverLiuyaqi** [comment]
RecordWave:v1.1.2

**Comment by ForeverLiuyaqi** [comment]
RecordWave:v1.1.2
Android7.1.2
Nexus 5X

**Comment by CarGuo** [comment]
resolveToWaveData list clone from mRecDataList， i m not sure why it ArrayIndexOutOfBounds?

**Comment by CarGuo** [comment]
try v1.1.3
