### ISSUE TITLE
Repeat the tape The abnormal    

### ISSUE THREAD

**Issue by alitong** [CarGuo/RecordWave#14]
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@f341e32
at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
at android.graphics.Canvas.drawBitmap(Canvas.java:1325)
at com.shuyu.waveview.AudioWaveView$drawThread.run(AudioWaveView.java:220)

**Comment by CarGuo** [comment]
can you reproduce in demo?  when AudioWaveView onDetachedFromWindow，bitmap will be recycled.
