### ISSUE TITLE
java.util.ConcurrentModificationException 

### ISSUE THREAD

**Issue by ErNaveen** [CarGuo/RecordWave#17]
java.util.ConcurrentModificationException 
 at java.util.ArrayList$Itr.next(ArrayList.java:837) 
 at  com.shuyu.waveview.AudioWaveView.resolveToWaveData(AudioWaveView.java:259)
 at com.shuyu.waveview.AudioWaveView.access$900(AudioWaveView.java:28)
 at com.shuyu.waveview.AudioWaveView$drawThread.run(AudioWaveView.java:192)

**Comment by CarGuo** [comment]
which version？

**Comment by ErNaveen** [comment]
Android 7.0

**Comment by CarGuo** [comment]
1.1.2？

**Comment by cisankit** [comment]
yes

**Comment by cisankit** [comment]
I m getting same error on android 7.0 with RecordWave version 1.1.2

**Comment by CarGuo** [comment]
try v1.1.3

**Comment by MagnifierSun** [comment]
我也发现了这个问题，大概是writeObj是在另一个线程做的，而arraylist不是线程安全的，就报错了

**Comment by CarGuo** [comment]
代码里应该加了锁啊
