### ISSUE TITLE
运行出错了，麻烦看下   Process: com.shuyu.app, PID: 8294 

### ISSUE THREAD

**Issue by alitong** [CarGuo/RecordWave#20]
# 作者您好，今天下载代码运行出错了
## # 只是修改播放语音的网络地址就出现下面的错误！
                                                             --------- beginning of crash
**06-30 10:05:42.654 8294-8526/com.shuyu.app E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                             Process: com.shuyu.app, PID: 8294
                                                             java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                 at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                 at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                 at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                 at java.lang.Thread.run(Thread.java:818)
                                                              Caused by: java.lang.IllegalArgumentException
                                                                 at android.media.MediaExtractor.getTrackFormatNative(Native Method)
                                                                 at android.media.MediaExtractor.getTrackFormat(MediaExtractor.java:269)
                                                                 at com.piterwilson.audio.MP3RadioStreamPlayer.decodeLoop(MP3RadioStreamPlayer.java:243)
                                                                 at com.piterwilson.audio.MP3RadioStreamPlayer.access$300(MP3RadioStreamPlayer.java:33)
                                                                 at com.piterwilson.audio.MP3RadioStreamPlayer$DecodeOperation.doInBackground(MP3RadioStreamPlayer.java:500)
                                                                 at com.piterwilson.audio.MP3RadioStreamPlayer$DecodeOperation.doInBackground(MP3RadioStreamPlayer.java:496)
                                                                 at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                 at java.lang.Thread.run(Thread.java:818)**

**Comment by CarGuo** [comment]
没看出问题在哪里。获取音频的流有问题？能提供下流URL吗？
