### ISSUE TITLE
在华为手机上遇到这个问题,请问有什么解决方法吗?谢谢

### ISSUE THREAD

**Issue by AndroidDevo** [CarGuo/RecordWave#27]
android.media.MediaCodec$CodecException: Error 0xfffffff3
	at android.media.MediaCodec.releaseOutputBuffer(Native Method)
	at android.media.MediaCodec.releaseOutputBuffer(MediaCodec.java:1082)
	at com.piterwilson.audio.MP3RadioStreamPlayer.m(MP3RadioStreamPlayer.java:407)
	at com.piterwilson.audio.MP3RadioStreamPlayer.b(MP3RadioStreamPlayer.java:33)
	at com.piterwilson.audio.MP3RadioStreamPlayer$b.a(MP3RadioStreamPlayer.java:499)
	at com.piterwilson.audio.MP3RadioStreamPlayer$b.doInBackground(MP3RadioStreamPlayer.java:495)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by CarGuo** [comment]
demo吗？
