### ISSUE TITLE
App is Crashing with Version 1.1.3

### ISSUE THREAD

**Issue by coderaviverma** [CarGuo/RecordWave#28]
Fatal Exception: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@f344cfc
       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
       at android.graphics.Canvas.drawBitmap(Canvas.java:1325)
       at com.shuyu.waveview.AudioWaveView$drawThread.run(AudioWaveView.java:232)

Class :
AudioWaveView.java line 232
com.shuyu.waveview.AudioWaveView$drawThread.run 

Operating System Version : 6.0.1
Device : Blackberry

Data from Crashlytics

**Comment by CarGuo** [comment]
i remenber  bitmap will be recycled when view detachedFromWindow , you may be stopView first
