### ISSUE TITLE
Player is getting crash on Audiowave recycle

### ISSUE THREAD

**Issue by coderaviverma** [CarGuo/RecordWave#39]
While frequently seekto the a duration it get crashes or starts from the 0 position. The error is somewhere in wave recycling. I can't see the error in log also.

Also please change the int parameter to long as after 33 Min Audio it stops as the it reaches the limit of integer Max. So i used your module in my project and modified it. Please also change this so I can directly use your project gradle. Thank you for Awesome library.

```
public void seekTo(long time) {
        if (time >= duration || pause) {
            return;
        }
        stop();
        seekOffsetFlag = true;
        this.seekOffset = time;
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                try {
                    play();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }, 300);
    }
```

**Comment by CarGuo** [comment]
ok，I will update seekTo function in 1.1.7
but i could‘t not reproduce the crashes .
wave recycling cause crash?

**Comment by coderaviverma** [comment]
I will debug and i will send you the error. I will install crashlystics in ur module then.

On 27 Feb 2018 1:39 p.m., Shuyu Guo <notifications@github.com> wrote:

ok，I will update seekTo function in 1.1.7
but i could‘t not reproduce the crashes .
wave recycling cause crash?

**Comment by coderaviverma** [comment]
Try to change the all int value to long.

**Comment by coderaviverma** [comment]
Hi,

I found the issue in 
```
MP3RadioStreamPlayer.java line 390
com.piterwilson.audio.MP3RadioStreamPlayer.decodeLoop
```

```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:309)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

```
Caused by java.lang.IllegalStateException: buffer is inaccessible
       at java.nio.DirectByteBuffer.checkIsAccessible(DirectByteBuffer.java:551)
       at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:112)
       at java.nio.ByteBuffer.get(ByteBuffer.java:376)
       at com.piterwilson.audio.MP3RadioStreamPlayer.decodeLoop(MP3RadioStreamPlayer.java:390)
       at com.piterwilson.audio.MP3RadioStreamPlayer.access$300(MP3RadioStreamPlayer.java:33)
       at com.piterwilson.audio.MP3RadioStreamPlayer$DecodeOperation.doInBackground(MP3RadioStreamPlayer.java:502)
       at com.piterwilson.audio.MP3RadioStreamPlayer$DecodeOperation.doInBackground(MP3RadioStreamPlayer.java:498)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

Please check this bug. It automatically gets crashed after stay on pause for some time or If we first open the player.

**Comment by CarGuo** [comment]
I have not idea , function  isAccessible() is @hide in DirectByteBuffer, I have no way to judge ` inaccessible`
try resolve it like this ??
```
                final byte[] chunk = new byte[info.size];
                boolean successBufferGet = true;
                try {
                    buf.get(chunk);
                    buf.clear();
                } catch (Exception e) {
                    successBufferGet = false;
                    e.printStackTrace();
                }
                if (successBufferGet && chunk.length > 0 && audioTrack != null && !doStop) {
```

i could‘t not reproduce the crashes , so I can't judge whether it is valid
