### ISSUE TITLE
列表中 使用MP3RadioStreamPlayer  练习点击 不同的item

### ISSUE THREAD

**Issue by duanhao** [CarGuo/RecordWave#6]
java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                       at android.os.AsyncTask$3.done(AsyncTask.java:304)
                                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:818)
                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.AudioTrack.write(byte[], int, int)' on a null object reference
                                                                       at com.piterwilson.audio.MP3RadioStreamPlayer.decodeLoop(MP3RadioStreamPlayer.java:387)
                                                                       at com.piterwilson.audio.MP3RadioStreamPlayer.access$300(MP3RadioStreamPlayer.java:33)
                                                                       at com.piterwilson.audio.MP3RadioStreamPlayer$DecodeOperation.doInBackground(MP3RadioStreamPlayer.java:494)
                                                                       at com.piterwilson.audio.MP3RadioStreamPlayer$DecodeOperation.doInBackground(MP3RadioStreamPlayer.java:490)
                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by duanhao** [comment]
我用的 1.0.8

**Comment by CarGuo** [comment]
播放器最好是单例一个的，不能再列表中new 多个，列表上个人还真没试过，这里看起来像是释放AudioTrack但是MP3Player还在跑
